#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 The Nova-Office contributors
#
# Write third_party/libreoffice/autogen.input from the Nova compliance-first
# configure flag set recorded in third_party/UPSTREAM_PIN (docs/licensing.md §5),
# plus any extra flags passed on the command line or in autogen.input.local.
#
# Usage: scripts/nova-autogen.sh [extra --configure --flags ...]

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PIN_FILE="third_party/UPSTREAM_PIN"
SUBMOD="third_party/libreoffice"
[[ -d "$SUBMOD" ]] || { echo "ERROR: $SUBMOD missing — run scripts/bootstrap-upstream.sh first" >&2; exit 1; }
[[ -f "$PIN_FILE" ]] || { echo "ERROR: $PIN_FILE missing" >&2; exit 1; }

# Extract the `configure_flags: >-` folded block from UPSTREAM_PIN.
FLAGS="$(awk '
  /^configure_flags:[[:space:]]*>-/ { grab=1; next }
  grab {
    if ($0 ~ /^[^[:space:]]/ && $0 !~ /^--/) { grab=0; next }
    gsub(/^[[:space:]]+/, ""); if ($0 != "") print
  }
' "$PIN_FILE")"

OUT="$SUBMOD/autogen.input"
{
  echo "# Generated by scripts/nova-autogen.sh from $PIN_FILE — edits go in autogen.input.local"
  echo "$FLAGS"
  [[ -n "${*:-}" ]] && printf '%s\n' "$@"
  if [[ -f "$SUBMOD/autogen.input.local" ]]; then
    echo "# --- from autogen.input.local ---"
    grep -v '^[[:space:]]*#' "$SUBMOD/autogen.input.local" || true
  fi
} > "$OUT"

echo "Wrote $OUT:"
sed 's/^/    /' "$OUT"
echo
echo "Next: (cd $SUBMOD && ./autogen.sh)  — see docs/build-<platform>.md"
