#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 The Nova-Office contributors
#
# Write third_party/libreoffice/autogen.input from the Nova compliance-first
# configure flag set recorded in third_party/UPSTREAM_PIN (docs/licensing.md §5),
# plus any extra flags passed on the command line or in autogen.input.local.
#
# Usage: scripts/nova-autogen.sh [extra --configure --flags ...]

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PIN_FILE="third_party/UPSTREAM_PIN"
SUBMOD="third_party/libreoffice"
[[ -d "$SUBMOD" ]] || { echo "ERROR: $SUBMOD missing — run scripts/bootstrap-upstream.sh first" >&2; exit 1; }
[[ -f "$PIN_FILE" ]] || { echo "ERROR: $PIN_FILE missing" >&2; exit 1; }

# Extract the `configure_flags: >-` folded block from UPSTREAM_PIN.
FLAGS="$(awk '
  /^configure_flags:[[:space:]]*>-/ { grab=1; next }
  grab {
    if ($0 ~ /^[^[:space:]]/ && $0 !~ /^--/) { grab=0; next }
    gsub(/^[[:space:]]+/, ""); if ($0 != "") print
  }
' "$PIN_FILE")"

# Branding flags generated from product/product.yaml (product name / vendor /
# privacy-policy URL). Verified against the pinned source: these are configure
# flags, not a config patch.
node scripts/gen-branding.mjs >/dev/null
BRANDING_FLAGS_FILE="product/generated/nova-configure-flags"

# The Nova settings schema (org.openoffice.Nova) ships via
# patches/0002-officecfg-add-nova-schema.patch — DEFERRED (.todo) until
# nova_theme needs it. When re-enabled, this copies Nova.xcs/.xcu into officecfg
# (canonical source: nova/nova_config/registry/).
if [[ -f patches/0002-officecfg-add-nova-schema.patch ]]; then
  mkdir -p "$SUBMOD/officecfg/registry/schema/org/openoffice" \
           "$SUBMOD/officecfg/registry/data/org/openoffice"
  cp nova/nova_config/registry/schema/org/openoffice/Nova.xcs \
     "$SUBMOD/officecfg/registry/schema/org/openoffice/Nova.xcs"
  cp nova/nova_config/registry/data/org/openoffice/Nova.xcu \
     "$SUBMOD/officecfg/registry/data/org/openoffice/Nova.xcu"
fi

# --- nova_theme: copy the module into the LO tree and give it the generated
# --- token header. Registration in RepositoryModule_host.mk is patch 0001.
if [[ -d nova/nova_theme ]]; then
  node scripts/build-tokens.mjs >/dev/null
  rm -rf "$SUBMOD/nova_theme"
  cp -r nova/nova_theme "$SUBMOD/nova_theme"
  mkdir -p "$SUBMOD/nova_theme/inc"
  cp nova/design-tokens/dist/NovaTokens.hxx "$SUBMOD/nova_theme/inc/NovaTokens.hxx"
  # the Jobs.xcu overlay that turns the job on
  mkdir -p "$SUBMOD/officecfg/registry/data/org/openoffice/Office"
  cp nova/nova_config/registry/data/org/openoffice/Office/Jobs.xcu \
     "$SUBMOD/officecfg/registry/data/org/openoffice/Office/Nova-Jobs.xcu" 2>/dev/null || true
  # one contextual toolbar instead of the stacked standard+formatting rows
  cp nova/nova_config/registry/data/org/openoffice/Office/UI.xcu \
     "$SUBMOD/officecfg/registry/data/org/openoffice/Office/Nova-UI.xcu" 2>/dev/null || true

  # Register the module + library in the build graph. patches/README lists this
  # as patch 0001, but a context diff against Repository.mk breaks on every
  # upstream reshuffle; an idempotent edit that fails loudly is sturdier and
  # keeps patches/ empty.
  RMH="$SUBMOD/RepositoryModule_host.mk"
  if ! grep -q 'nova_theme' "$RMH"; then
    perl -0pi -e 's/^(\tpostprocess \\\n)/\tnova_theme \\\n$1/m' "$RMH"
    grep -q 'nova_theme' "$RMH" || {
      echo "ERROR: could not register nova_theme in RepositoryModule_host.mk;" >&2
      echo "       the 'postprocess' anchor moved — see docs/shell-implementation-plan.md" >&2
      exit 1; }
    echo "[nova-autogen] registered nova_theme module"
  fi
  # nova_theme is an ordinary office component library, so it belongs in the
  # OOOLIBS/ooo install set — the block that carries uui, utl and friends. That
  # header appears several times; the one followed by "avmedia" is the right one.
  REPO="$SUBMOD/Repository.mk"
  if ! grep -q 'nova_theme' "$REPO"; then
    perl -0pi -e 's/^(\$\(eval \$\(call gb_Helper_register_libraries_for_install,OOOLIBS,ooo, \\\n[ \t]*avmedia \\\n)/$1\tnova_theme \\\n/m' "$REPO"
    grep -q 'nova_theme' "$REPO" || {
      echo "ERROR: could not register nova_theme library in Repository.mk;" >&2
      echo "       the OOOLIBS,ooo/avmedia anchor moved — see docs/shell-implementation-plan.md" >&2
      exit 1; }
    echo "[nova-autogen] registered nova_theme library"
  fi
fi

OUT="$SUBMOD/autogen.input"
{
  echo "# Generated by scripts/nova-autogen.sh from $PIN_FILE — edits go in autogen.input.local"
  echo "$FLAGS"
  [[ -f "$BRANDING_FLAGS_FILE" ]] && grep -v '^[[:space:]]*#' "$BRANDING_FLAGS_FILE"
  [[ -n "${*:-}" ]] && printf '%s\n' "$@"
  if [[ -f "$SUBMOD/autogen.input.local" ]]; then
    echo "# --- from autogen.input.local ---"
    grep -v '^[[:space:]]*#' "$SUBMOD/autogen.input.local" || true
  fi
} > "$OUT"

echo "Wrote $OUT:"
sed 's/^/    /' "$OUT"
echo
echo "Next: (cd $SUBMOD && ./autogen.sh)  — see docs/build-<platform>.md"
